pipeline {
    agent any
stages {
        stage('Checkout') {
            steps {
                // Pull your project from GitHub
                checkout scm
            }
        }
 stage('Install Node deps (Cypress)') {
            steps {
                sh 'npm install'
            }
        }
 stage('Run Cypress tests') {
            steps {
                // Run ALL Cypress tests in headless mode
                sh 'npx cypress run'
            }
        }
stage('Run Selenium tests (Maven)') {
            steps {
                dir('seleniumJava') {
                    sh 'mvn -B test'
                }
            }
        }
    }

    post {
        always {
            // Archive Selenium JUnit/TestNG XML results so Jenkins can show a test report
            junit 'seleniumJava/target/surefire-reports/*.xml'

        }
    }
}